# Generated by Django 5.1.6 on 2025-02-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_product_quantity_supplierprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprice',
            old_name='supplier_name',
            new_name='supplier',
        ),
    ]
