# Generated by Django 5.1.6 on 2025-02-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_rename_supplier_name_supplierprice_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierPrice',
        ),
    ]
