# Generated by Django 5.1.6 on 2025-02-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_price_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='best_price_supplier',
        ),
    ]
