# Generated by Django 5.1.6 on 2025-02-24 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_product_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'supplier', 'date_added')},
        ),
    ]
